### ISSUE TITLE
Do not work when redirection is enabled

### ISSUE THREAD

**Issue by antohami** [realdigger/SMF-Redirector#2]
Do not work when redirection is enabled
Example:
[anchor=l22][/anchor][iurl=#ll22][2][/iurl]
The link looks like:
site.com/forums/index.php?topic=2674.0#post_l22
And if redirection is enabled, the link looks like
site.com/forums/index.php?action=go;url=aHR0cDovLyNsMjI=
When you click on a link, nothing happens.

It is necessary that the redirection does not extend to the anchors.

**Comment by realdigger** [comment]
Fixed with 1.2.1 version.

**Comment by antohami** [comment]
The problem is not solved!

There are two anchors in the text. The term and its decoding at the end of the post
Anchor code:
`[Anchor = ll22] [/ anchor] [iurl = # l22] [2] [/ iurl]`

In html it looks like:
`<a href="#post_ll22" class="bbc_link"> [2] </a>`
After enabling redirection, the link spoils and takes the form:
`<a href="#ll22" class="bbc_link"> [2] </a>`

**Comment by realdigger** [comment]
Try 1.2.2 version.

**Comment by antohami** [comment]
Thanks! Working.
